In [1]:
#One line at a time

In [2]:
import pandas as pd 
import numpy as np

In [3]:
first_dataset = pd.read_csv("static\IPL_Ball_by_Ball_2008_2022.csv")
second_dataset = pd.read_csv("static\IPL_Matches_2008_2022.csv")

first_dataset.head()

,ID,innings,overs,ballnumber,batter,bowler,non-striker,extra_type,batsman_run,extras_run,total_run,non_boundary,isWicketDelivery,player_out,kind,fielders_involved,BattingTeam
0,1312200,1,0,1,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals
1,1312200,1,0,2,YBK Jaiswal,Mohammed Shami,JC Buttler,legbyes,0,1,1,0,0,NaN,NaN,NaN,Rajasthan Royals
2,1312200,1,0,3,JC Buttler,Mohammed Shami,YBK Jaiswal,NaN,1,0,1,0,0,NaN,NaN,NaN,Rajasthan Royals
3,1312200,1,0,4,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals
4,1312200,1,0,5,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals

In [4]:
second_dataset.head()

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma
4,1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,N,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan

In [5]:
first_dataset.columns

Index(['ID', 'innings', 'overs', 'ballnumber', 'batter', 'bowler',
       'non-striker', 'extra_type', 'batsman_run', 'extras_run', 'total_run',
       'non_boundary', 'isWicketDelivery', 'player_out', 'kind',
       'fielders_involved', 'BattingTeam'],
      dtype='object')

In [6]:
total_runs = first_dataset.groupby(['ID','innings']).sum()['total_run'].add(1).reset_index()

In [7]:
total_runs

           ID  innings  total_run
0      335982        1        223
1      335982        2         83
2      335983        1        241
3      335983        2        208
4      335984        1        130
...       ...      ...        ...
1923  1312198        2        194
1924  1312199        1        158
1925  1312199        2        162
1926  1312200        1        131
1927  1312200        2        134

[1928 rows x 3 columns]

In [8]:
total_runs = total_runs[total_runs['innings']==1]

In [9]:
match_df = second_dataset.merge(total_runs[['ID','total_run']],left_on='ID',right_on='ID')

In [10]:
match_df

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,...,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2,total_run
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,...,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon,131
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,...,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon,158
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,...,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough,208
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,...,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma,189
4,1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,...,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan,158
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
945,335986,Kolkata,2008-04-20,2007/08,4,Kolkata Knight Riders,Deccan Chargers,Eden Gardens,Deccan Chargers,bat,...,Kolkata Knight Riders,Wickets,5.0,NaN,DJ Hussey,"['WP Saha', 'BB McCullum', 'RT Ponting', 'SC G...","['AC Gilchrist', 'Y Venugopal Rao', 'VVS Laxma...",BF Bowden,K Hariharan,111
946,335985,Mumbai,2008-04-20,2007/08,5,Mumbai Indians,Royal Challengers Bangalore,Wankhede Stadium,Mumbai Indians,bat,...,Royal Challengers Bangalore,Wickets,5.0,NaN,MV Boucher,"['L Ronchi', 'ST Jayasuriya', 'DJ Thornely', '...","['S Chanderpaul', 'R Dravid', 'LRPL Taylor', '...",SJ Davis,DJ Harper,166
947,335984,Delhi,2008-04-19,2007/08,3,Delhi Daredevils,Rajasthan Royals,Feroz Shah Kotla,Rajasthan Royals,bat,...,Delhi Daredevils,Wickets,9.0,NaN,MF Maharoof,"['G Gambhir', 'V Sehwag', 'S Dhawan', 'MK Tiwa...","['T Kohli', 'YK Pathan', 'SR Watson', 'M Kaif'...",Aleem Dar,GA Pratapkumar,130
948,335983,Chandigarh,2008-04-19,2007/08,2,Kings XI Punjab,Chennai Super Kings,"Punjab Cricket Association Stadium, Mohali",Chennai Super Kings,bat,...,Chennai Super Kings,Runs,33.0,NaN,MEK Hussey,"['K Goel', 'JR Hopes', 'KC Sangakkara', 'Yuvra...","['PA Patel', 'ML Hayden', 'MEK Hussey', 'MS Dh...",MR Benson,SL Shastri,241
949,335982,Bangalore,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,...,Kolkata Knight Riders,Runs,140.0,NaN,BB McCullum,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",Asad Rauf,RE Koertzen,223

In [11]:
match_df['Team1'].value_counts()

Royal Challengers Bangalore    126
Mumbai Indians                 112
Chennai Super Kings            111
Kolkata Knight Riders          105
Kings XI Punjab                 92
Rajasthan Royals                89
Delhi Daredevils                85
Sunrisers Hyderabad             69
Deccan Chargers                 39
Delhi Capitals                  29
Pune Warriors                   23
Punjab Kings                    18
Gujarat Lions                   16
Lucknow Super Giants             8
Gujarat Titans                   7
Rising Pune Supergiant           7
Rising Pune Supergiants          7
Kochi Tuskers Kerala             7
Name: Team1, dtype: int64

In [12]:
match_df['Team1'] = match_df['Team1'].replace('Delhi Daredevils','Delhi Capitals')
match_df['Team2'] = match_df['Team2'].replace('Delhi Daredevils','Delhi Capitals')

match_df['Team1'] = match_df['Team1'].replace('Deccan Chargers','Sunrisers Hyderabad')
match_df['Team2'] = match_df['Team2'].replace('Deccan Chargers','Sunrisers Hyderabad')

match_df['Team1'] = match_df['Team1'].replace('Kings XI Punjab','Punjab Kings')
match_df['Team2'] = match_df['Team2'].replace('Kings XI Punjab','Punjab Kings')

In [13]:
match_df['Team1'].value_counts()

Royal Challengers Bangalore    126
Delhi Capitals                 114
Mumbai Indians                 112
Chennai Super Kings            111
Punjab Kings                   110
Sunrisers Hyderabad            108
Kolkata Knight Riders          105
Rajasthan Royals                89
Pune Warriors                   23
Gujarat Lions                   16
Lucknow Super Giants             8
Gujarat Titans                   7
Rising Pune Supergiant           7
Rising Pune Supergiants          7
Kochi Tuskers Kerala             7
Name: Team1, dtype: int64

In [14]:
teams = ['Kolkata Knight Riders', 
         'Chennai Super Kings',
         'Punjab Kings', 
         'Rajasthan Royals',
         'Mumbai Indians',
         'Delhi Capitals',
         'Royal Challengers Bangalore',
         'Sunrisers Hyderabad',
         'Lucknow Super Giants',
         'Gujarat Titans'
         ]

In [15]:
match_df = match_df[match_df['Team1'].isin(teams)]
match_df = match_df[match_df['Team2'].isin(teams)]

In [16]:
match_df['Team1'].value_counts()

Royal Challengers Bangalore    118
Chennai Super Kings            107
Delhi Capitals                 106
Punjab Kings                   103
Mumbai Indians                 102
Sunrisers Hyderabad            101
Kolkata Knight Riders           98
Rajasthan Royals                85
Lucknow Super Giants             8
Gujarat Titans                   7
Name: Team1, dtype: int64

In [17]:
match_df.shape

(835, 21)

In [18]:
match_df = match_df[['ID','City','WinningTeam','total_run', 'Team1', 'Team2']]

In [19]:
match_df.shape

(835, 6)

In [108]:
second_innings = match_df.merge(first_dataset,on='ID')
second_innings

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,...,extra_type,batsman_run,extras_run,total_run_y,non_boundary,isWicketDelivery,player_out,kind,fielders_involved,BattingTeam
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,...,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals
1,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,...,legbyes,0,1,1,0,0,NaN,NaN,NaN,Rajasthan Royals
2,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,...,NaN,1,0,1,0,0,NaN,NaN,NaN,Rajasthan Royals
3,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,...,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals
4,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,...,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
225949,335982,Bangalore,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,...,legbyes,0,1,1,0,0,NaN,NaN,NaN,Royal Challengers Bangalore
225950,335982,Bangalore,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,...,NaN,1,0,1,0,0,NaN,NaN,NaN,Royal Challengers Bangalore
225951,335982,Bangalore,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,...,NaN,0,0,0,0,0,NaN,NaN,NaN,Royal Challengers Bangalore
225952,335982,Bangalore,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,...,wides,0,1,1,0,0,NaN,NaN,NaN,Royal Challengers Bangalore
225953,335982,Bangalore,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,...,NaN,0,0,0,0,1,SB Joshi,caught,BB McCullum,Royal Challengers Bangalore

In [109]:
second_innings = second_innings[second_innings['innings']==2]
second_innings.shape

(108910, 37)

In [110]:
second_innings

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,...,extra_type,batsman_run,extras_run,total_run_y,non_boundary,isWicketDelivery,player_out,kind,fielders_involved,BattingTeam
120,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,...,NaN,0,0,0,0,0,NaN,NaN,NaN,Gujarat Titans
121,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,...,NaN,0,0,0,0,0,NaN,NaN,NaN,Gujarat Titans
122,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,...,NaN,1,0,1,0,0,NaN,NaN,NaN,Gujarat Titans
123,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,...,NaN,0,0,0,0,0,NaN,NaN,NaN,Gujarat Titans
124,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,...,NaN,0,0,0,0,0,NaN,NaN,NaN,Gujarat Titans
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
225949,335982,Bangalore,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,...,legbyes,0,1,1,0,0,NaN,NaN,NaN,Royal Challengers Bangalore
225950,335982,Bangalore,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,...,NaN,1,0,1,0,0,NaN,NaN,NaN,Royal Challengers Bangalore
225951,335982,Bangalore,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,...,NaN,0,0,0,0,0,NaN,NaN,NaN,Royal Challengers Bangalore
225952,335982,Bangalore,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,...,wides,0,1,1,0,0,NaN,NaN,NaN,Royal Challengers Bangalore
225953,335982,Bangalore,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,...,NaN,0,0,0,0,1,SB Joshi,caught,BB McCullum,Royal Challengers Bangalore

In [111]:
second_innings['Team1'] = second_innings['Team1'].replace('Delhi Daredevils','Delhi Capitals')
second_innings['Team2'] = second_innings['Team2'].replace('Delhi Daredevils','Delhi Capitals')

second_innings['Team1'] = second_innings['Team1'].replace('Deccan Chargers','Sunrisers Hyderabad')
second_innings['Team2'] = second_innings['Team2'].replace('Deccan Chargers','Sunrisers Hyderabad')

second_innings['Team1'] = second_innings['Team1'].replace('Kings XI Punjab','Punjab Kings')
second_innings['Team2'] = second_innings['Team2'].replace('Kings XI Punjab','Punjab Kings')

C:\Users\Sandesh Pargaonkar\AppData\Local\Temp\ipykernel_12376\340332489.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  second_innings['Team1'] = second_innings['Team1'].replace('Delhi Daredevils','Delhi Capitals')
C:\Users\Sandesh Pargaonkar\AppData\Local\Temp\ipykernel_12376\340332489.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  second_innings['Team2'] = second_innings['Team2'].replace('Delhi Daredevils','Delhi Capitals')
C:\Users\Sandesh Pargaonkar\AppData\Local\Temp\ipykernel_12376\340332489.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  second_innings['Team1'] = second_innings['Team1'].replace('Deccan Chargers','Sunrisers Hyderabad')
C:\Users\Sandesh Pargaonkar\AppData\Local\Temp\ipykernel_12376\340332489.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  second_innings['Team2'] = second_innings['Team2'].replace('Deccan Chargers','Sunrisers Hyderabad')
C:\Users\Sandesh Pargaonkar\AppData\Local\Temp\ipykernel_12376\340332489.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  second_innings['Team1'] = second_innings['Team1'].replace('Kings XI Punjab','Punjab Kings')
C:\Users\Sandesh Pargaonkar\AppData\Local\Temp\ipykernel_12376\340332489.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  second_innings['Team2'] = second_innings['Team2'].replace('Kings XI Punjab','Punjab Kings')

In [112]:
second_innings['Team1'].value_counts()

Royal Challengers Bangalore    14182
Chennai Super Kings            13142
Mumbai Indians                 13102
Delhi Capitals                 12870
Punjab Kings                   12613
Sunrisers Hyderabad            12469
Kolkata Knight Riders          11826
Rajasthan Royals               10194
Pune Warriors                   2651
Gujarat Lions                   1800
Lucknow Super Giants             968
Rising Pune Supergiants          809
Gujarat Titans                   790
Rising Pune Supergiant           776
Kochi Tuskers Kerala             718
Name: Team1, dtype: int64

In [113]:
second_innings.columns

Index(['ID', 'City', 'Date', 'Season', 'MatchNumber', 'Team1', 'Team2',
       'Venue', 'TossWinner', 'TossDecision', 'SuperOver', 'WinningTeam',
       'WonBy', 'Margin', 'method', 'Player_of_Match', 'Team1Players',
       'Team2Players', 'Umpire1', 'Umpire2', 'total_run_x', 'innings', 'overs',
       'ballnumber', 'batter', 'bowler', 'non-striker', 'extra_type',
       'batsman_run', 'extras_run', 'total_run_y', 'non_boundary',
       'isWicketDelivery', 'player_out', 'kind', 'fielders_involved',
       'BattingTeam'],
      dtype='object')

In [114]:
second_innings.shape

(108910, 37)

In [115]:
# Function to determine the bowling team
def determine_bowling_team(row):
    if row['BattingTeam'] == row['Team1']:
        return row['Team2']
    else:
        return row['Team1']

# Create the new 'BowlingTeam' column
second_innings['BowlingTeam'] = second_innings.apply(determine_bowling_team, axis=1)

C:\Users\Sandesh Pargaonkar\AppData\Local\Temp\ipykernel_12376\1658040854.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  second_innings['BowlingTeam'] = second_innings.apply(determine_bowling_team, axis=1)

In [116]:
second_innings.tail(103)

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,...,batsman_run,extras_run,total_run_y,non_boundary,isWicketDelivery,player_out,kind,fielders_involved,BattingTeam,BowlingTeam
225727,335983,Chandigarh,2008-04-19,2007/08,2,Punjab Kings,Chennai Super Kings,"Punjab Cricket Association Stadium, Mohali",Chennai Super Kings,bat,...,1,0,1,0,0,NaN,NaN,NaN,Kings XI Punjab,Punjab Kings
225728,335983,Chandigarh,2008-04-19,2007/08,2,Punjab Kings,Chennai Super Kings,"Punjab Cricket Association Stadium, Mohali",Chennai Super Kings,bat,...,0,0,0,0,0,NaN,NaN,NaN,Kings XI Punjab,Punjab Kings
225853,335982,Bangalore,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,...,1,0,1,0,0,NaN,NaN,NaN,Royal Challengers Bangalore,Kolkata Knight Riders
225854,335982,Bangalore,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,...,0,1,1,0,0,NaN,NaN,NaN,Royal Challengers Bangalore,Kolkata Knight Riders
225855,335982,Bangalore,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,...,0,0,0,0,0,NaN,NaN,NaN,Royal Challengers Bangalore,Kolkata Knight Riders
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
225949,335982,Bangalore,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,...,0,1,1,0,0,NaN,NaN,NaN,Royal Challengers Bangalore,Kolkata Knight Riders
225950,335982,Bangalore,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,...,1,0,1,0,0,NaN,NaN,NaN,Royal Challengers Bangalore,Kolkata Knight Riders
225951,335982,Bangalore,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,...,0,0,0,0,0,NaN,NaN,NaN,Royal Challengers Bangalore,Kolkata Knight Riders
225952,335982,Bangalore,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,...,0,1,1,0,0,NaN,NaN,NaN,Royal Challengers Bangalore,Kolkata Knight Riders
225953,335982,Bangalore,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,...,0,0,0,0,1,SB Joshi,caught,BB McCullum,Royal Challengers Bangalore,Kolkata Knight Riders

In [117]:
second_innings['BattingTeam'] = second_innings['BattingTeam'].replace('Delhi Daredevils','Delhi Capitals')
second_innings['BowlingTeam'] = second_innings['BowlingTeam'].replace('Delhi Daredevils','Delhi Capitals')

second_innings['BattingTeam'] = second_innings['BattingTeam'].replace('Deccan Chargers','Sunrisers Hyderabad')
second_innings['BowlingTeam'] = second_innings['BowlingTeam'].replace('Deccan Chargers','Sunrisers Hyderabad')

second_innings['BattingTeam'] = second_innings['BattingTeam'].replace('Kings XI Punjab','Punjab Kings')
second_innings['BowlingTeam'] = second_innings['BowlingTeam'].replace('Kings XI Punjab','Punjab Kings')

C:\Users\Sandesh Pargaonkar\AppData\Local\Temp\ipykernel_12376\1361729818.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  second_innings['BattingTeam'] = second_innings['BattingTeam'].replace('Delhi Daredevils','Delhi Capitals')
C:\Users\Sandesh Pargaonkar\AppData\Local\Temp\ipykernel_12376\1361729818.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  second_innings['BowlingTeam'] = second_innings['BowlingTeam'].replace('Delhi Daredevils','Delhi Capitals')
C:\Users\Sandesh Pargaonkar\AppData\Local\Temp\ipykernel_12376\1361729818.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  second_innings['BattingTeam'] = second_innings['BattingTeam'].replace('Deccan Chargers','Sunrisers Hyderabad')
C:\Users\Sandesh Pargaonkar\AppData\Local\Temp\ipykernel_12376\1361729818.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  second_innings['BowlingTeam'] = second_innings['BowlingTeam'].replace('Deccan Chargers','Sunrisers Hyderabad')
C:\Users\Sandesh Pargaonkar\AppData\Local\Temp\ipykernel_12376\1361729818.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  second_innings['BattingTeam'] = second_innings['BattingTeam'].replace('Kings XI Punjab','Punjab Kings')
C:\Users\Sandesh Pargaonkar\AppData\Local\Temp\ipykernel_12376\1361729818.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  second_innings['BowlingTeam'] = second_innings['BowlingTeam'].replace('Kings XI Punjab','Punjab Kings')

In [118]:
second_innings

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,...,batsman_run,extras_run,total_run_y,non_boundary,isWicketDelivery,player_out,kind,fielders_involved,BattingTeam,BowlingTeam
120,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,...,0,0,0,0,0,NaN,NaN,NaN,Gujarat Titans,Rajasthan Royals
121,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,...,0,0,0,0,0,NaN,NaN,NaN,Gujarat Titans,Rajasthan Royals
122,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,...,1,0,1,0,0,NaN,NaN,NaN,Gujarat Titans,Rajasthan Royals
123,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,...,0,0,0,0,0,NaN,NaN,NaN,Gujarat Titans,Rajasthan Royals
124,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,...,0,0,0,0,0,NaN,NaN,NaN,Gujarat Titans,Rajasthan Royals
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
225949,335982,Bangalore,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,...,0,1,1,0,0,NaN,NaN,NaN,Royal Challengers Bangalore,Kolkata Knight Riders
225950,335982,Bangalore,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,...,1,0,1,0,0,NaN,NaN,NaN,Royal Challengers Bangalore,Kolkata Knight Riders
225951,335982,Bangalore,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,...,0,0,0,0,0,NaN,NaN,NaN,Royal Challengers Bangalore,Kolkata Knight Riders
225952,335982,Bangalore,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,...,0,1,1,0,0,NaN,NaN,NaN,Royal Challengers Bangalore,Kolkata Knight Riders
225953,335982,Bangalore,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,...,0,0,0,0,1,SB Joshi,caught,BB McCullum,Royal Challengers Bangalore,Kolkata Knight Riders

In [119]:
second_innings['BowlingTeam'].unique()

array(['Rajasthan Royals', 'Royal Challengers Bangalore',
       'Sunrisers Hyderabad', 'Delhi Capitals', 'Chennai Super Kings',
       'Gujarat Titans', 'Lucknow Super Giants', 'Kolkata Knight Riders',
       'Punjab Kings', 'Mumbai Indians', 'Rising Pune Supergiant',
       'Gujarat Lions', 'Rising Pune Supergiants', 'Pune Warriors',
       'Kochi Tuskers Kerala'], dtype=object)

In [120]:
second_innings['current_Score'] = second_innings.groupby('ID').cumsum()['total_run_y']
second_innings

C:\Users\Sandesh Pargaonkar\AppData\Local\Temp\ipykernel_12376\3076402150.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  second_innings['current_Score'] = second_innings.groupby('ID').cumsum()['total_run_y']

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,...,extras_run,total_run_y,non_boundary,isWicketDelivery,player_out,kind,fielders_involved,BattingTeam,BowlingTeam,current_Score
120,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,...,0,0,0,0,NaN,NaN,NaN,Gujarat Titans,Rajasthan Royals,0
121,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,...,0,0,0,0,NaN,NaN,NaN,Gujarat Titans,Rajasthan Royals,0
122,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,...,0,1,0,0,NaN,NaN,NaN,Gujarat Titans,Rajasthan Royals,1
123,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,...,0,0,0,0,NaN,NaN,NaN,Gujarat Titans,Rajasthan Royals,1
124,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,...,0,0,0,0,NaN,NaN,NaN,Gujarat Titans,Rajasthan Royals,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
225949,335982,Bangalore,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,...,1,1,0,0,NaN,NaN,NaN,Royal Challengers Bangalore,Kolkata Knight Riders,80
225950,335982,Bangalore,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,...,0,1,0,0,NaN,NaN,NaN,Royal Challengers Bangalore,Kolkata Knight Riders,81
225951,335982,Bangalore,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,...,0,0,0,0,NaN,NaN,NaN,Royal Challengers Bangalore,Kolkata Knight Riders,81
225952,335982,Bangalore,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,...,1,1,0,0,NaN,NaN,NaN,Royal Challengers Bangalore,Kolkata Knight Riders,82
225953,335982,Bangalore,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,...,0,0,0,1,SB Joshi,caught,BB McCullum,Royal Challengers Bangalore,Kolkata Knight Riders,82

In [121]:
second_innings['runs_left'] = second_innings['total_run_x'] - second_innings['current_Score']
second_innings

C:\Users\Sandesh Pargaonkar\AppData\Local\Temp\ipykernel_12376\802083827.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  second_innings['runs_left'] = second_innings['total_run_x'] - second_innings['current_Score']

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,...,total_run_y,non_boundary,isWicketDelivery,player_out,kind,fielders_involved,BattingTeam,BowlingTeam,current_Score,runs_left
120,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,...,0,0,0,NaN,NaN,NaN,Gujarat Titans,Rajasthan Royals,0,131
121,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,...,0,0,0,NaN,NaN,NaN,Gujarat Titans,Rajasthan Royals,0,131
122,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,...,1,0,0,NaN,NaN,NaN,Gujarat Titans,Rajasthan Royals,1,130
123,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,...,0,0,0,NaN,NaN,NaN,Gujarat Titans,Rajasthan Royals,1,130
124,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,...,0,0,0,NaN,NaN,NaN,Gujarat Titans,Rajasthan Royals,1,130
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
225949,335982,Bangalore,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,...,1,0,0,NaN,NaN,NaN,Royal Challengers Bangalore,Kolkata Knight Riders,80,143
225950,335982,Bangalore,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,...,1,0,0,NaN,NaN,NaN,Royal Challengers Bangalore,Kolkata Knight Riders,81,142
225951,335982,Bangalore,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,...,0,0,0,NaN,NaN,NaN,Royal Challengers Bangalore,Kolkata Knight Riders,81,142
225952,335982,Bangalore,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,...,1,0,0,NaN,NaN,NaN,Royal Challengers Bangalore,Kolkata Knight Riders,82,141
225953,335982,Bangalore,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,...,0,0,1,SB Joshi,caught,BB McCullum,Royal Challengers Bangalore,Kolkata Knight Riders,82,141

In [122]:
second_innings['balls_left'] = 126 - (second_innings['overs']*6 +second_innings['ballnumber'])
second_innings

C:\Users\Sandesh Pargaonkar\AppData\Local\Temp\ipykernel_12376\2820591732.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  second_innings['balls_left'] = 126 - (second_innings['overs']*6 +second_innings['ballnumber'])

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,...,non_boundary,isWicketDelivery,player_out,kind,fielders_involved,BattingTeam,BowlingTeam,current_Score,runs_left,balls_left
120,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,...,0,0,NaN,NaN,NaN,Gujarat Titans,Rajasthan Royals,0,131,125
121,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,...,0,0,NaN,NaN,NaN,Gujarat Titans,Rajasthan Royals,0,131,124
122,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,...,0,0,NaN,NaN,NaN,Gujarat Titans,Rajasthan Royals,1,130,123
123,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,...,0,0,NaN,NaN,NaN,Gujarat Titans,Rajasthan Royals,1,130,122
124,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,...,0,0,NaN,NaN,NaN,Gujarat Titans,Rajasthan Royals,1,130,121
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
225949,335982,Bangalore,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,...,0,0,NaN,NaN,NaN,Royal Challengers Bangalore,Kolkata Knight Riders,80,143,37
225950,335982,Bangalore,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,...,0,0,NaN,NaN,NaN,Royal Challengers Bangalore,Kolkata Knight Riders,81,142,36
225951,335982,Bangalore,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,...,0,0,NaN,NaN,NaN,Royal Challengers Bangalore,Kolkata Knight Riders,81,142,35
225952,335982,Bangalore,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,...,0,0,NaN,NaN,NaN,Royal Challengers Bangalore,Kolkata Knight Riders,82,141,35
225953,335982,Bangalore,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,...,0,1,SB Joshi,caught,BB McCullum,Royal Challengers Bangalore,Kolkata Knight Riders,82,141,34

In [123]:
second_innings.columns

Index(['ID', 'City', 'Date', 'Season', 'MatchNumber', 'Team1', 'Team2',
       'Venue', 'TossWinner', 'TossDecision', 'SuperOver', 'WinningTeam',
       'WonBy', 'Margin', 'method', 'Player_of_Match', 'Team1Players',
       'Team2Players', 'Umpire1', 'Umpire2', 'total_run_x', 'innings', 'overs',
       'ballnumber', 'batter', 'bowler', 'non-striker', 'extra_type',
       'batsman_run', 'extras_run', 'total_run_y', 'non_boundary',
       'isWicketDelivery', 'player_out', 'kind', 'fielders_involved',
       'BattingTeam', 'BowlingTeam', 'current_Score', 'runs_left',
       'balls_left'],
      dtype='object')

In [124]:
# Select the columns of interest
columns_to_check = ['current_Score', 'runs_left', 'balls_left']

# Check how many values in each column are negative
negative_counts = second_innings[columns_to_check].lt(0).sum()

# Display the counts
print("Number of negative values in each column:")
print(negative_counts)

Number of negative values in each column:
current_Score      0
runs_left        306
balls_left         0
dtype: int64

In [125]:
second_innings['player_out'] = second_innings['player_out'].fillna("0")
second_innings['player_out'] = second_innings['player_out'].apply(lambda x:x if x=="0" else "1")
second_innings['player_out'] = second_innings['player_out'].astype('int')
wickets = second_innings.groupby('ID').cumsum()['player_out']
second_innings['wickets_remaining'] = 10-wickets
second_innings

C:\Users\Sandesh Pargaonkar\AppData\Local\Temp\ipykernel_12376\1997531377.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  second_innings['player_out'] = second_innings['player_out'].fillna("0")
C:\Users\Sandesh Pargaonkar\AppData\Local\Temp\ipykernel_12376\1997531377.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  second_innings['player_out'] = second_innings['player_out'].apply(lambda x:x if x=="0" else "1")
C:\Users\Sandesh Pargaonkar\AppData\Local\Temp\ipykernel_12376\1997531377.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  second_innings['player_out'] = second_innings['player_out'].astype('int')
C:\Users\Sandesh Pargaonkar\AppData\Local\Temp\ipykernel_12376\1997531377.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  second_innings['wickets_remaining'] = 10-wickets

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,...,isWicketDelivery,player_out,kind,fielders_involved,BattingTeam,BowlingTeam,current_Score,runs_left,balls_left,wickets_remaining
120,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,...,0,0,NaN,NaN,Gujarat Titans,Rajasthan Royals,0,131,125,10
121,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,...,0,0,NaN,NaN,Gujarat Titans,Rajasthan Royals,0,131,124,10
122,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,...,0,0,NaN,NaN,Gujarat Titans,Rajasthan Royals,1,130,123,10
123,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,...,0,0,NaN,NaN,Gujarat Titans,Rajasthan Royals,1,130,122,10
124,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,...,0,0,NaN,NaN,Gujarat Titans,Rajasthan Royals,1,130,121,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
225949,335982,Bangalore,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,...,0,0,NaN,NaN,Royal Challengers Bangalore,Kolkata Knight Riders,80,143,37,1
225950,335982,Bangalore,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,...,0,0,NaN,NaN,Royal Challengers Bangalore,Kolkata Knight Riders,81,142,36,1
225951,335982,Bangalore,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,...,0,0,NaN,NaN,Royal Challengers Bangalore,Kolkata Knight Riders,81,142,35,1
225952,335982,Bangalore,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,...,0,0,NaN,NaN,Royal Challengers Bangalore,Kolkata Knight Riders,82,141,35,1
225953,335982,Bangalore,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,...,1,1,caught,BB McCullum,Royal Challengers Bangalore,Kolkata Knight Riders,82,141,34,0

In [130]:
second_innings['crr'] = round((second_innings['current_Score']*6)/(120 - second_innings['balls_left']),2)
second_innings['rrr'] = round((second_innings['runs_left']*6)/(second_innings['balls_left']),2)
second_innings

C:\Users\Sandesh Pargaonkar\AppData\Local\Temp\ipykernel_12376\1691903609.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  second_innings['crr'] = round((second_innings['current_Score']*6)/(120 - second_innings['balls_left']),2)
C:\Users\Sandesh Pargaonkar\AppData\Local\Temp\ipykernel_12376\1691903609.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  second_innings['rrr'] = round((second_innings['runs_left']*6)/(second_innings['balls_left']),2)

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,...,kind,fielders_involved,BattingTeam,BowlingTeam,current_Score,runs_left,balls_left,wickets_remaining,crr,rrr
120,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,...,NaN,NaN,Gujarat Titans,Rajasthan Royals,0,131,125,10,-0.00,6.29
121,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,...,NaN,NaN,Gujarat Titans,Rajasthan Royals,0,131,124,10,-0.00,6.34
122,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,...,NaN,NaN,Gujarat Titans,Rajasthan Royals,1,130,123,10,-2.00,6.34
123,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,...,NaN,NaN,Gujarat Titans,Rajasthan Royals,1,130,122,10,-3.00,6.39
124,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,...,NaN,NaN,Gujarat Titans,Rajasthan Royals,1,130,121,10,-6.00,6.45
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
225949,335982,Bangalore,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,...,NaN,NaN,Royal Challengers Bangalore,Kolkata Knight Riders,80,143,37,1,5.78,23.19
225950,335982,Bangalore,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,...,NaN,NaN,Royal Challengers Bangalore,Kolkata Knight Riders,81,142,36,1,5.79,23.67
225951,335982,Bangalore,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,...,NaN,NaN,Royal Challengers Bangalore,Kolkata Knight Riders,81,142,35,1,5.72,24.34
225952,335982,Bangalore,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,...,NaN,NaN,Royal Challengers Bangalore,Kolkata Knight Riders,82,141,35,1,5.79,24.17
225953,335982,Bangalore,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,...,caught,BB McCullum,Royal Challengers Bangalore,Kolkata Knight Riders,82,141,34,0,5.72,24.88

In [132]:
def winner(team):
    return 1 if team['BattingTeam'] == team['WinningTeam'] else 0

In [165]:
second_innings['results'] = second_innings.apply(winner,axis=1)
second_innings

C:\Users\Sandesh Pargaonkar\AppData\Local\Temp\ipykernel_12376\3111665595.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  second_innings['results'] = second_innings.apply(winner,axis=1)

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,...,fielders_involved,BattingTeam,BowlingTeam,current_Score,runs_left,balls_left,wickets_remaining,crr,rrr,results
120,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,...,NaN,Gujarat Titans,Rajasthan Royals,0,131,125,10,-0.00,6.29,1
121,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,...,NaN,Gujarat Titans,Rajasthan Royals,0,131,124,10,-0.00,6.34,1
122,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,...,NaN,Gujarat Titans,Rajasthan Royals,1,130,123,10,-2.00,6.34,1
123,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,...,NaN,Gujarat Titans,Rajasthan Royals,1,130,122,10,-3.00,6.39,1
124,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,...,NaN,Gujarat Titans,Rajasthan Royals,1,130,121,10,-6.00,6.45,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
225949,335982,Bangalore,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,...,NaN,Royal Challengers Bangalore,Kolkata Knight Riders,80,143,37,1,5.78,23.19,0
225950,335982,Bangalore,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,...,NaN,Royal Challengers Bangalore,Kolkata Knight Riders,81,142,36,1,5.79,23.67,0
225951,335982,Bangalore,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,...,NaN,Royal Challengers Bangalore,Kolkata Knight Riders,81,142,35,1,5.72,24.34,0
225952,335982,Bangalore,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,...,NaN,Royal Challengers Bangalore,Kolkata Knight Riders,82,141,35,1,5.79,24.17,0
225953,335982,Bangalore,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,...,BB McCullum,Royal Challengers Bangalore,Kolkata Knight Riders,82,141,34,0,5.72,24.88,0

In [140]:
required_data = second_innings[['BattingTeam','BowlingTeam','City','runs_left','balls_left','wickets_remaining','total_run_x','crr','rrr','results']]
required_data

,BattingTeam,BowlingTeam,City,runs_left,balls_left,wickets_remaining,total_run_x,crr,rrr,results
120,Gujarat Titans,Rajasthan Royals,Ahmedabad,131,125,10,131,-0.00,6.29,1
121,Gujarat Titans,Rajasthan Royals,Ahmedabad,131,124,10,131,-0.00,6.34,1
122,Gujarat Titans,Rajasthan Royals,Ahmedabad,130,123,10,131,-2.00,6.34,1
123,Gujarat Titans,Rajasthan Royals,Ahmedabad,130,122,10,131,-3.00,6.39,1
124,Gujarat Titans,Rajasthan Royals,Ahmedabad,130,121,10,131,-6.00,6.45,1
...,...,...,...,...,...,...,...,...,...,...
225949,Royal Challengers Bangalore,Kolkata Knight Riders,Bangalore,143,37,1,223,5.78,23.19,0
225950,Royal Challengers Bangalore,Kolkata Knight Riders,Bangalore,142,36,1,223,5.79,23.67,0
225951,Royal Challengers Bangalore,Kolkata Knight Riders,Bangalore,142,35,1,223,5.72,24.34,0
225952,Royal Challengers Bangalore,Kolkata Knight Riders,Bangalore,141,35,1,223,5.79,24.17,0
225953,Royal Challengers Bangalore,Kolkata Knight Riders,Bangalore,141,34,0,223,5.72,24.88,0

In [141]:
required_data = required_data.replace([np.inf, -np.inf], np.nan)
required_data = required_data.dropna()

In [142]:
required_data = required_data[required_data['crr'] >= 0]

In [149]:
columns_to_check = ['runs_left', 'balls_left', 'wickets_remaining', 'total_run_x', 'crr', 'rrr', 'results']

required_data = required_data[~(required_data[columns_to_check] < 0).any(axis=1)]

In [168]:
required_data.head()

,BattingTeam,BowlingTeam,City,runs_left,balls_left,wickets_remaining,total_run_x,crr,rrr,results
120,Gujarat Titans,Rajasthan Royals,Ahmedabad,131,125,10,131,-0.0,6.29,1
121,Gujarat Titans,Rajasthan Royals,Ahmedabad,131,124,10,131,-0.0,6.34,1
126,Gujarat Titans,Rajasthan Royals,Ahmedabad,126,119,10,131,30.0,6.35,1
127,Gujarat Titans,Rajasthan Royals,Ahmedabad,122,118,10,131,27.0,6.20,1
128,Gujarat Titans,Rajasthan Royals,Ahmedabad,122,117,10,131,18.0,6.26,1

In [173]:
# Assuming your DataFrame is named 'df'
required_data.rename(columns={'BattingTeam': 'batting_team', 'BowlingTeam': 'bowling_team', 'City': 'city'}, inplace=True)
required_data

C:\Users\Sandesh Pargaonkar\AppData\Local\Temp\ipykernel_12376\545772493.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  required_data.rename(columns={'BattingTeam': 'batting_team', 'BowlingTeam': 'bowling_team', 'City': 'city'}, inplace=True)

,batting_team,bowling_team,city,runs_left,balls_left,wickets_remaining,total_run_x,crr,rrr,results
120,Gujarat Titans,Rajasthan Royals,Ahmedabad,131,125,10,131,-0.00,6.29,1
121,Gujarat Titans,Rajasthan Royals,Ahmedabad,131,124,10,131,-0.00,6.34,1
126,Gujarat Titans,Rajasthan Royals,Ahmedabad,126,119,10,131,30.00,6.35,1
127,Gujarat Titans,Rajasthan Royals,Ahmedabad,122,118,10,131,27.00,6.20,1
128,Gujarat Titans,Rajasthan Royals,Ahmedabad,122,117,10,131,18.00,6.26,1
...,...,...,...,...,...,...,...,...,...,...
225949,Royal Challengers Bangalore,Kolkata Knight Riders,Bangalore,143,37,1,223,5.78,23.19,0
225950,Royal Challengers Bangalore,Kolkata Knight Riders,Bangalore,142,36,1,223,5.79,23.67,0
225951,Royal Challengers Bangalore,Kolkata Knight Riders,Bangalore,142,35,1,223,5.72,24.34,0
225952,Royal Challengers Bangalore,Kolkata Knight Riders,Bangalore,141,35,1,223,5.79,24.17,0
225953,Royal Challengers Bangalore,Kolkata Knight Riders,Bangalore,141,34,0,223,5.72,24.88,0

In [174]:
numeric = required_data[['runs_left', 'balls_left', 'wickets_remaining', 'total_run_x', 'crr', 'rrr', 'results']]
has_infinite_values = np.any(np.isinf(numeric))

# Check for negative values in the entire DataFrame
has_negative_values = (numeric < 0).any().any()

# Check for null values in the entire DataFrame
has_null_values = numeric.isnull().any().any()

# Display the results
print(f"Has Infinite Values: {has_infinite_values}")
print(f"Has Negative Values: {has_negative_values}")
print(f"Has Null Values: {has_null_values}")

Has Infinite Values: False
Has Negative Values: False
Has Null Values: False

In [175]:
required_data.to_csv("csv2008-22.csv", index=False)

In [176]:
from sklearn.model_selection import train_test_split

In [178]:
x = required_data.iloc[:, :-1]
y = required_data.iloc[:,-1]
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.25,random_state=100)
x_train.head()

,batting_team,bowling_team,city,runs_left,balls_left,wickets_remaining,total_run_x,crr,rrr
55831,Chennai Super Kings,Kolkata Knight Riders,Chennai,40,53,8,109,6.18,4.53
164545,Chennai Super Kings,Royal Challengers Bangalore,Chennai,55,26,7,206,9.64,12.69
224293,Mumbai Indians,Chennai Super Kings,Chennai,79,41,6,209,9.87,11.56
71944,Sunrisers Hyderabad,Punjab Kings,Chandigarh,65,30,6,194,8.60,13.00
18075,Kolkata Knight Riders,Chennai Super Kings,Dubai,137,88,10,193,10.50,9.34

In [182]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
trf = ColumnTransformer([
    ('trf',OneHotEncoder(sparse=False,drop='first'),['batting_team','bowling_team','city'])
],
remainder='passthrough')

In [183]:
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline

pipe = Pipeline([
    ('step1',trf),
    ('step2',LogisticRegression(solver='liblinear'))
])

In [184]:
pipe.fit(x_train,y_train)

Pipeline(steps=[('step1',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('trf',
                                                  OneHotEncoder(drop='first',
                                                                sparse=False),
                                                  ['batting_team',
                                                   'bowling_team', 'city'])])),
                ('step2', LogisticRegression(solver='liblinear'))])

In [185]:
y_pred = pipe.predict(x_test)

In [186]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.8304319531440657

In [187]:
pipe.predict_proba(x_test)[0]

array([0.99626214, 0.00373786])

In [188]:
import pickle
pickle.dump(pipe,open('pipe.pkl','wb'))

In [189]:
from sklearn.ensemble import RandomForestClassifier

ra_pipe = Pipeline([
    ('step1',trf),
    ('step2',RandomForestClassifier())
])

ra_pipe.fit(x_train,y_train)

ra_y_pred = ra_pipe.predict(x_test)

accuracy_score(y_test,ra_y_pred)

0.9986984462702351

In [190]:
import pickle
pickle.dump(ra_pipe,open('ra_pipe.pkl','wb'))

In [191]:
required_data.head(2)

,batting_team,bowling_team,city,runs_left,balls_left,wickets_remaining,total_run_x,crr,rrr,results
120,Gujarat Titans,Rajasthan Royals,Ahmedabad,131,125,10,131,-0.0,6.29,1
121,Gujarat Titans,Rajasthan Royals,Ahmedabad,131,124,10,131,-0.0,6.34,1

In [193]:
data = pd.read_csv('csv2023.csv')
data.rename(columns={'max_total_run_x': 'total_run_x'}, inplace=True)
data.head(2)

,batting_team,bowling_team,city,runs_left,balls_left,wickets_remaining,total_run_x,crr,rrr,results
0,Gujarat Titans,Chennai Super Kings,Ahmedabad,179,125,10,179,-0.0,8.59,1
1,Gujarat Titans,Chennai Super Kings,Ahmedabad,179,124,10,179,-0.0,8.66,1

In [195]:
df = pd.concat([required_data, data], ignore_index=True)
df

,batting_team,bowling_team,city,runs_left,balls_left,wickets_remaining,total_run_x,crr,rrr,results
0,Gujarat Titans,Rajasthan Royals,Ahmedabad,131,125,10,131,-0.00,6.29,1
1,Gujarat Titans,Rajasthan Royals,Ahmedabad,131,124,10,131,-0.00,6.34,1
2,Gujarat Titans,Rajasthan Royals,Ahmedabad,126,119,10,131,30.00,6.35,1
3,Gujarat Titans,Rajasthan Royals,Ahmedabad,122,118,10,131,27.00,6.20,1
4,Gujarat Titans,Rajasthan Royals,Ahmedabad,122,117,10,131,18.00,6.26,1
...,...,...,...,...,...,...,...,...,...,...
106599,Chennai Super Kings,Gujarat Titans,Ahmedabad,56,40,5,215,11.92,8.40,1
106600,Chennai Super Kings,Gujarat Titans,Ahmedabad,55,39,5,215,11.85,8.46,1
106601,Chennai Super Kings,Gujarat Titans,Ahmedabad,54,38,5,215,11.78,8.53,1
106602,Chennai Super Kings,Gujarat Titans,Ahmedabad,48,37,5,215,12.07,7.78,1
106603,Chennai Super Kings,Gujarat Titans,Ahmedabad,44,36,5,215,12.21,7.33,1

In [196]:
df.to_csv('dataset.csv')

In [198]:
x = df.iloc[:, :-1]
y = df.iloc[:,-1]
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.25,random_state=100)
x_train.head()

,batting_team,bowling_team,city,runs_left,balls_left,wickets_remaining,total_run_x,crr,rrr
83100,Kolkata Knight Riders,Delhi Capitals,Delhi,63,25,4,178,7.26,15.12
45186,Rajasthan Royals,Sunrisers Hyderabad,Mumbai,125,61,7,202,7.83,12.30
63509,Delhi Capitals,Delhi Capitals,Pune,117,98,8,163,12.55,7.16
72577,Royal Challengers Bangalore,Punjab Kings,Dharamsala,178,77,6,233,7.67,13.87
33729,Gujarat Lions,Royal Challengers Bangalore,Bangalore,54,70,8,135,9.72,4.63

In [199]:
from sklearn.ensemble import RandomForestClassifier

ra_pipe = Pipeline([
    ('step1',trf),
    ('step2',RandomForestClassifier())
])

ra_pipe.fit(x_train,y_train)

ra_y_pred = ra_pipe.predict(x_test)

accuracy_score(y_test,ra_y_pred)

0.9990994709391767

In [200]:
import pickle
pickle.dump(ra_pipe,open('ra_pipe.pkl','wb'))